# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e53ada9a5649e979b602e2236b473bb5c206f7ce0cc44926a35c7d163f7198872d1020e1c8c85148ee6fd9a6940d86b13a91b8b411607b087a1807ababf9555

test:
  secret_key_base: 7a62b33d01a047068b0b84b1e4044988c0c245d3dbfd2ed9f319b899e77ab63370b78e65e3ac58684dc0240c547fb3dd32540c9ea21a3f1841216a9792fd5b6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
